language: python
python:
  - "2.7"

# command to install dependencies
install: 
  - "pip install invoke"
  - "pip install flake8"
  - "pip install -r requirements.txt -t vendor"

before_script:
  - "wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.20.zip -nv"
  - "unzip -q google_appengine_1.9.20.zip"

env:
  - "GAE_SDK_ROOT=google_appengine"

# command to run tests
script:
  - inv flake8
  - inv test

